# Generated by Django 5.2.6 on 2025-10-06 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_blog',
            field=models.CharField(default='Blog', max_length=255),
        ),
    ]
